### ISSUE TITLE
11月23日の課題

### ISSUE THREAD

**Issue by projectormato** [projectormato/TDD#4]
* ステートマシン図(プロジェクト情報)
```
[*] --> プロジェクト有効状態 : プロジェクト作成
プロジェクト有効状態 --> プロジェクト有効状態 : 編集
プロジェクト有効状態 : do/プロジェクト情報更新
プロジェクト有効状態 --> プロジェクト無効状態 : プロジェクト削除
```

**Comment by yt1316** [comment]
@startuml
[*] -> 未ログイン状態 : 新規登録
未ログイン状態 -> アカウント有効状態 : 初回ログイン
アカウント有効状態 -> アカウント無効状態 : 停止など
アカウント無効状態 -> アカウント有効状態 : 再度有効化処理
 
未ログイン状態 : exit / パスワードを変更
未ログイン状態 -> アカウント有効状態 : [パスワードを変更しない]
@enduml

**Comment by YuMuuu** [comment]
@startuml
class project as "プロジェクト"{
    -プロジェクト名
    
    +プロジェクト プロジェクト情報を取得する()
    }


class task as "タスク"{
    -int 状態
    -String 内容
    
    }


class user as "利用者"{
    -id
    -passward
    -name
    
    +利用者 利用者情報を取得する()
    }
class admin as "管理者"{
    -id
    -passward
    -name
    
    +void プロジェクトを管理する()
    +void 利用者を管理する()
    }


project - task : < 所有する 
user - project : < 所有する 
@enduml
